feat: add expense predictor
moleus/iot-heating-system pull request #14
Opened 2024-05-20 22:55 UTC by Korako2

2024-05-20 22:55 UTC, Korako2 commented
@moleus

2024-05-21 05:48 UTC, moleus requested changes

2024-05-21 05:48 UTC, moleus commented on cmd/expense_predictor/main.go
> +	pflag.String("mqtt_publish_fuel_expenses_prediction_topic", "predictions/fuel_expenses", "Fuel expenses prediction writing topic")
Хорошо бы вынести названия топиков в commons, как сделано у других серисов

2024-05-21 05:48 UTC, moleus commented on pkg/common/types.go
> +
Я не уверен, что метрики будут считываться из такого объекта. Лучше использовать один массив с объектами, как в hourForecast

2024-05-21 10:42 UTC, Korako2 commented
@moleus

2024-05-21 11:33 UTC, moleus approved these changes

2024-05-21 11:34 UTC, merged